import styled from "styled-components";
import Head from "next/head";
import Header from "../components/Header";
import Main from "../components/Main";

export default function Home(): JSX.Element {
  return (
    <StyledDiv>
      <Head>
        <title>MatchBall</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Main />
    </StyledDiv>
  );
}

const StyledDiv = styled.div`
  height: 100vh;
  display: grid;
  grid-template-rows: 10rem auto;
  padding: 0;
`;
