import Head from "next/head";
import Header from "../components/Header";
import Navigation from "../components/Navigation";
import styled from "styled-components";
import Link from "next/link";
import MiniCard from "../components/MiniCard";

export default function ScoreForm(): JSX.Element {
  function handleSubmit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault();
  }
  return (
    <StyledDiv>
      <Head>
        <title>MatchBall</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header teaser={"Scores"} />
      <section>
        <div>
          <MiniCard
            name={"Andy"}
            cloudinarySrc={
              "https://res.cloudinary.com/doryasyte/image/upload/v1672829815/MatchBall/profiles/llfjwvlfiwtquwny8ckp.jpg"
            }
          />
          <MiniCard
            name={"Merle"}
            cloudinarySrc={
              "https://res.cloudinary.com/doryasyte/image/upload/v1672829815/MatchBall/profiles/llfjwvlfiwtquwny8ckp.jpg"
            }
          />
        </div>
        <div>
          <span>VS</span>
          <MiniCard
            name={"Julia"}
            cloudinarySrc={
              "https://res.cloudinary.com/doryasyte/image/upload/v1672829815/MatchBall/profiles/llfjwvlfiwtquwny8ckp.jpg"
            }
          />
          <MiniCard
            name={"Jan"}
            cloudinarySrc={
              "https://res.cloudinary.com/doryasyte/image/upload/v1672829815/MatchBall/profiles/llfjwvlfiwtquwny8ckp.jpg"
            }
          />
        </div>
      </section>
      <section>
        <form onSubmit={handleSubmit}>
          <label htmlFor="pointsLeftSide">Points</label>
          <input
            type="number"
            name="pointsLeftSide"
            id="pointsLeftSide"
            aria-label="points for the Team on the left side"
          />
          <label htmlFor="pointsRightSide">Points</label>
          <input
            type="number"
            name="pointsRightSide"
            id="pointsRightSide"
            aria-label="points for the Team on the right side"
          />
          <button>Save</button>
        </form>
      </section>

      <Navigation />
    </StyledDiv>
  );
}

const StyledDiv = styled.div``;
