import { useState } from "react";
import { Member } from "../interfaces/interfaces";
import Head from "next/head";
import Header from "../components/Header";
import Link from "next/link";
import Main from "../components/Main";
import { Criteria } from "../interfaces/interfaces";

type TeamChoiceFormProps = {
  desiredPlayer: Criteria;
  setDesiredPlayer: any;
  allPlayers: Member[];
  setAllPlayers: any;
};

export default function TeamChoiceForm({
  desiredPlayer,
  setDesiredPlayer,
  allPlayers,
  setAllPlayers,
}: TeamChoiceFormProps): JSX.Element {
  return (
    <div>
      <Head>
        <title>MatchBall</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header teaser={"Choose the teams"} />
      <Main
        desiredPlayer={desiredPlayer}
        setDesiredPlayer={setDesiredPlayer}
        allPlayers={allPlayers}
        setAllPlayers={setAllPlayers}
        isSelectable={true}
      />
      <button type="submit">
        <Link href={"/scoreForm"}>Continue</Link>
      </button>
      <button>
        <Link href={"/games"}>Back</Link>
      </button>
    </div>
  );
}
