import getAllTeams from "../utils/getAllTeams";
import { useEffect, useState } from "react";
import Head from "next/head";
import Header from "../components/Header";
import { Team } from "../interfaces/interfaces";
import Link from "next/link";
import TeamComponent from "../components/TeamComponent";
import styled from "styled-components";

export default function TeamChoiceForm(): JSX.Element {
  const [teams, setTeams] = useState<[Team]>([
    { players: [], points: 0, id: "", wins: 0, games: 0 },
  ]);

  useEffect(() => {
    async function fetchTeamsAndUpdateTeamState() {
      const fetchedTeams = await getAllTeams();
      setTeams(fetchedTeams);
    }
    fetchTeamsAndUpdateTeamState();
  }, []);

  return (
    <>
      <Head>
        <title>MatchBall</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header teaser={"Teams"} />
      <section>
        <StyledUl data-cy="team-list">
          {teams.map((team) => {
            return (
              <li key={team.id}>
                <TeamComponent team={team} isClickable={true} />
              </li>
            );
          })}
        </StyledUl>
      </section>

      <button>
        <Link href={"/scoreForm"} data-cy="scoreForm-navigation">
          Continue
        </Link>
      </button>
      <button>
        <Link href={"/teamChoiceForm"}>Create a new team</Link>
      </button>
      <button>
        <Link href={"/games"}>Back</Link>
      </button>
    </>
  );
}
const StyledUl = styled.ul`
  list-style-type: none;
`;
