import { useEffect } from "react";
import { Member } from "../interfaces/interfaces";
import Head from "next/head";
import Header from "../components/Header";
import Link from "next/link";
import Main from "../components/Main";
import { Criteria } from "../interfaces/interfaces";
import postTeam from "../utils/postTeam";

type TeamChoiceFormProps = {
  desiredPlayer: Criteria;
  setDesiredPlayer: any;
  allPlayers: Member[];
  setAllPlayers: any;
};

export default function TeamChoiceForm({
  desiredPlayer,
  setDesiredPlayer,
  allPlayers,
  setAllPlayers,
}: TeamChoiceFormProps): JSX.Element {
  useEffect(() => {
    localStorage.removeItem("newTeam");
  }, []);

  async function handlePostTeam() {
    const newTeam = localStorage.getItem("newTeam");
    if (newTeam) {
      const newTeamObj = JSON.parse(newTeam);
      postTeam(newTeamObj);
    }
  }

  return (
    <div>
      <Head>
        <title>MatchBall</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header teaser={"Choose the teams"} />
      <Main
        desiredPlayer={desiredPlayer}
        setDesiredPlayer={setDesiredPlayer}
        allPlayers={allPlayers}
        setAllPlayers={setAllPlayers}
        isSelectable={true}
      />
      <button onClick={handlePostTeam}>
        <Link href={"/teamChoice"}>Continue</Link>
      </button>
      <button>
        <Link href={"/games"}>Back to games</Link>
      </button>
    </div>
  );
}
