import getAllTeams from "../utils/getAllTeams";
import { useEffect, useState } from "react";
import Head from "next/head";
import Header from "../components/Header";
import { Team } from "../interfaces/interfaces";
import Link from "next/link";
import TeamComponent from "../components/TeamComponent";
import postTeam from "../utils/postTeam";

export default function TeamChoiceForm(): JSX.Element {
  const [teams, setTeams] = useState<[Team]>([
    { players: [], points: 0, id: "", wins: 0, games: 0 },
  ]);

  useEffect(() => {
    async function getAllTeamsAndUpdateDBWithNewTeamIfThereIsOne() {
      const fetchedTeams = await getAllTeams();
      const newTeam = localStorage.getItem("newTeam");
      if (newTeam) {
        const newTeamObj = JSON.parse(newTeam);
        const AllTeams = [newTeamObj, ...fetchedTeams];
        postTeam(newTeamObj);
        setTeams(AllTeams);

        console.log("Teams + newTeam: ", AllTeams);
      } else {
        setTeams(fetchedTeams);
        console.log("Teams: ", fetchedTeams);
      }
    }
    getAllTeamsAndUpdateDBWithNewTeamIfThereIsOne();
  }, []);

  return (
    <>
      <Head>
        <title>MatchBall</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header teaser={"Teams"} />
      <section>
        {teams.map((team) => {
          return <TeamComponent team={team} key={team.id} isClickable={true} />;
        })}
      </section>
      <button>
        <Link href={"/scoreForm"}>Continue</Link>
      </button>
      <button>
        <Link href={"/teamChoiceForm"}>Create a new team</Link>
      </button>
      <button>
        <Link href={"/games"}>Back</Link>
      </button>
    </>
  );
}
