import getAllTeams from "../utils/getAllTeams";
import { useEffect, useState } from "react";
import Head from "next/head";
import Header from "../components/Header";
import { Team } from "../interfaces/interfaces";
import Link from "next/link";
import TeamComponent from "../components/TeamComponent";
import styled from "styled-components";
import Image from "next/image";

export default function TeamChoiceForm(): JSX.Element {
  const [teams, setTeams] = useState<[Team]>([
    { players: [], points: 0, id: "", wins: 0, games: 0 },
  ]);

  useEffect(() => {
    async function fetchTeamsAndUpdateTeamState() {
      const fetchedTeams = await getAllTeams();
      setTeams(fetchedTeams);
    }
    fetchTeamsAndUpdateTeamState();
  }, []);

  return (
    <StyledDiv>
      <Head>
        <title>MatchBall</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header teaser={"Teams"} />
      <section>
        <StyledUl data-cy="team-list">
          {teams.map((team) => {
            return (
              <li key={team.id}>
                <TeamComponent team={team} isClickable={true} />
              </li>
            );
          })}
        </StyledUl>
      </section>
      <StyledNav>
        <StyledLink href={"/games"} aria-label="Back to games">
          <Image
            src="/arrow-back.svg"
            alt="arrow back"
            width={50}
            height={50}
          />
        </StyledLink>

        <StyledLink href={"/teamChoiceForm"} aria-label="Create new team">
          <Image
            src="/plus-rectangle_1.svg"
            alt="plus"
            width={50}
            height={50}
          />
        </StyledLink>

        <StyledLink
          href={"/scoreForm"}
          data-cy="scoreForm-navigation"
          aria-label="Continue to scores"
        >
          <Image
            src="/arrow-forward.svg"
            alt="arrow forwards"
            width={50}
            height={50}
          />
        </StyledLink>
      </StyledNav>
    </StyledDiv>
  );
}
const StyledUl = styled.ul`
  list-style-type: none;
  display: flex;
  flex-direction: column;
  gap: 1rem;
  overflow-y: scroll;
  height: 70vh;
  width: 100vw;
`;

const StyledDiv = styled.div`
  height: 100vh;
  width: 100vw;
  padding: 0;
  background-image: url("/playergroup.jpg");
  background-size: cover;
  background-attachment: fixed;
  background-position: bottom;
  background-repeat: no-repeat;
  font-size: 20px;
  font-family: baloo_2;
`;

const StyledLink = styled(Link)`
  height: 10vh;
  width: 30vw;
  padding-top: 0.2em;
  border-radius: 25px;
  transition: scale 0.15s ease;
  -webkit-tap-highlight-color: transparent;

  :active {
    scale: 1.1;
  }
`;

const StyledNav = styled.nav`
  display: flex;
  justify-content: space-around;
  position: fixed;
  bottom: 0;
  left: 7%;
  width: 100vw;
`;
